version: "3.9"

services:
  opnsense:
    image: opnsense/core
    privileged: true
    ports:
      - "443:443"
      - "22:22"
    networks:
      - sdwan

  pihole:
    image: pihole/pihole
    environment:
      TZ: 'Africa/Accra'
      WEBPASSWORD: 'admin'
    ports:
      - "8080:80"
    networks:
      - sdwan

  edge-node1:
    build: ./edge-node
    networks:
      - sdwan

networks:
  sdwan:
    driver: bridge
